export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const categories = [
  { key: 0, cat: "Electronics" },
  { key: 1, cat: "phones" },
  { key: 2, cat: "Laptops" },
  { key: 3, cat: "Appliances" },
  { key: 4, cat: "Glocerry" },
  { key: 5, cat: "Books" },
  { key: 6, cat: "Toys" },
  { key: 7, cat: "Clothes" },
  { key: 8, cat: "Shoes" },
  { key: 9, cat: "Food" },
  { key: 10, cat: "Others" },
];

export const brandTypes = [
  { key: 0, cat: "Plug" },
  { key: 1, cat: "Store" },
  { key: 2, cat: "Mall" },
  { key: 3, cat: "Restaurants" },
];
