export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAIL = "CREATE_BRAND_FAIL";

export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";

export const GET_MYBRAND_REQUEST = "GET_MYBRAND_REQUEST";
export const GET_MYBRAND_SUCCESS = "GET_MYBRAND_SUCCESS";
export const GET_MYBRAND_FAIL = "GET_MYBRAND_FAIL";

export const GET_BRAND_DETAIL_REQUEST = "GET_BRAND_DETAIL_REQUEST";
export const GET_BRAND_DETAIL_SUCCESS = "GET_BRAND_DETAIL_SUCCESS";
export const GET_BRAND_DETAIL_FAIL = "GET_BRAND_DETAIL_FAIL";

export const GET_BRAND_PRODUCTS_REQUEST = "GET_BRAND_PRODUCTS_REQUEST";
export const GET_BRAND_PRODUCTS_SUCCESS = "GET_BRAND_PRODUCTS_SUCCESS";
export const GET_BRAND_PRODUCTS_FAIL = "GET_BRAND_PRODUCTS_FAIL";

export const GET_BRAND_ID_REQUEST = "GET_BRAND_ID_REQUEST";
export const GET_BRAND_ID_SUCCESS = "GET_BRAND_ID_SUCCESS";
export const GET_BRAND_ID_FAIL = "GET_BRAND_ID_FAIL";

export const ALL_BRAND_REQUEST = "ALL_BRAND_REQUEST";
export const ALL_BRAND_SUCCESS = "ALL_BRAND_SUCCESS";
export const ALL_BRAND_FAIL = "ALL_BRAND_FAIL";

export const ADMIN_ALL_BRAND_REQUEST = "ADMIN_ALL_BRAND_REQUEST";
export const ADMIN_ALL_BRAND_SUCCESS = "ADMIN_ALL_BRAND_SUCCESS";
export const ADMIN_ALL_BRAND_FAIL = "ADMIN_ALL_BRAND_FAIL";

export const BRANDS_IN_LOCATION_REQUEST = "BRANDS_IN_LOCATION_REQUEST";
export const BRANDS_IN_LOCATION_SUCCESS = "BRANDS_IN_LOCATION_SUCCESS";
export const BRANDS_IN_LOCATION_FAIL = "BRANDS_IN_LOCATION_FAIL";

export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_RESET = "UPDATE_BRAND_RESET";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";

//seller section of brands  reducer
export const SAVE_CREATE_BRAND_INFO = "SAVE_CREATE_BRAND_INFO";
export const CLEAR_ERROR = "CLEAR_ERROR";
