export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";

export const GET_BRAND_DETAIL_REQUEST = "GET_BRAND_DETAIL_REQUEST";
export const GET_BRAND_DETAIL_SUCCESS = "GET_BRAND_DETAIL_SUCCESS";
export const GET_BRAND_DETAIL_FAIL = "GET_BRAND_DETAIL_FAIL";

export const GET_BRAND_PRODUCTS_REQUEST = "GET_BRAND_PRODUCTS_REQUEST";
export const GET_BRAND_PRODUCTS_SUCCESS = "GET_BRAND_PRODUCTS_SUCCESS";
export const GET_BRAND_PRODUCTS_FAIL = "GET_BRAND_PRODUCTS_FAIL";

export const ALL_BRAND_REQUEST = "ALL_BRAND_REQUEST";
export const ALL_BRAND_SUCCESS = "ALL_BRAND_SUCCESS";
export const ALL_BRAND_FAIL = "ALL_BRAND_FAIL";

export const BRANDS_IN_LOCATION_REQUEST = "BRANDS_IN_LOCATION_REQUEST";
export const BRANDS_IN_LOCATION_SUCCESS = "BRANDS_IN_LOCATION_SUCCESS";
export const BRANDS_IN_LOCATION_FAIL = "BRANDS_IN_LOCATION_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
