export const GET_TRENDING_PRODUCT_REQUEST = "GET_TRENDING_PRODUCT_REQUEST";
export const GET_TRENDING_PRODUCT_SUCCESS = "GET_TRENDING_PRODUCT_SUCCESS";
export const GET_TRENDING_PRODUCT_FAIL = "GET_TRENDING_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const GET_RECOMMENDED_PRODUCTS_REQUEST =
  "GET_RECOMMENDED_PRODUCTS_REQUEST";
export const GET_RECOMMENDED_PRODUCTS_SUCCESS =
  "GET_RECOMMENDED_PRODUCTS_SUCCESS";
export const GET_RECOMMENDED_PRODUCTS_FAIL = "GET_RECOMMENDED_PRODUCTS_FAIL";

export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS";
export const PRODUCT_REVIEW_FAIL = "PRODUCT_REVIEW_FAIL";
export const PRODUCT_REVIEW_RESET = "PRODUCT_REVIEW_RESET";

export const CREATE_PRODUCTS_REQUEST = "CREATE_PRODUCTS_REQUEST";
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCTS_FAIL = "CREATE_PRODUCTS_FAIL";
export const CREATE_PRODUCTS_RESET = "CREATE_PRODUCTS_RESET";

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAIL = "DELETE_PRODUCTS_FAIL";
export const DELETE_PRODUCTS_RESET = "DELETE_PRODUCTS_RESET";

export const UPDATE_PRODUCTS_REQUEST = "UPDATE_PRODUCTS_REQUEST";
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCTS_FAIL = "UPDATE_PRODUCTS_FAIL";
export const UPDATE_PRODUCTS_RESET = "UPDATE_PRODUCTS_RESET";

export const NEW_PRODUCTS_REQUEST = "NEW_PRODUCTS_REQUEST";
export const NEW_PRODUCTS_SUCCESS = "NEW_PRODUCTS_SUCCESS";
export const NEW_PRODUCTS_FAIL = "NEW_PRODUCTS_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_BOOK_FAIL";

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";

export const ADMIN_GET_PRODUCTS_REQUEST = "ADMIN_GET_PRODUCTS_REQUEST";
export const ADMIN_GET_PRODUCTS_SUCCESS = "ADMIN_GET_PRODUCTS_SUCCESS";
export const ADMIN_GET_PRODUCTS_FAIL = "ADMIN_GET_PRODUCTS_FAIL";
